name: face-swap-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.1
  - pillow=10.0.1
  - opencv=4.8.1
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.23.2
    - pydantic==2.4.2
    - insightface==0.7.3
    - onnx==1.15.0
    - onnxruntime==1.16.1
    - requests==2.31.0
    - python-multipart==0.0.6
    - scikit-image==0.22.0
