[build]
base_image = "ubuntu:20.04"
dockerfile = "Dockerfile.fixed"
python_version = "3.8"
cuda_version = "11.8"

[build.env]
DEBIAN_FRONTEND = "noninteractive"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[deploy]
min_workers = 0
max_workers = 3
idle_timeout = 300
max_concurrency_per_worker = 1

[deploy.resources]
cpu = 2
memory = 8
gpu_type = "NVIDIA GeForce RTX 4090"
gpu_count = 1

[deploy.env]
MODEL_PATH = "/app/inswapper_128.fp16.onnx"
PYTHONPATH = "/app"

[handler]
file = "main_fixed.py"
method = "runsync"